"use client";

import { useState, useMemo } from "react";

// ─── Types ──────────────────────────────────────────────────────────────────
type SubToken = { text: string; saliency: number; idx: number; charStart: number; charEnd: number };
type GroupedWord = {
  originalWord: string; tokens: SubToken[]; totalSaliency: number;
  avgSaliency: number; maxAbsSaliency: number; isFragmented: boolean; wordIdx: number;
};
type TokenizerConfig = { name: string; vocabSize: string; type: string; color: string };
type CaseStudy = { label: string; text: string; perturbation: string; perturbed: string; desc: string };

const TOKENIZERS: TokenizerConfig[] = [
  { name: "BPE-8K",       vocabSize: "8,192",   type: "BPE",   color: "#818cf8" },
  { name: "BPE-16K",      vocabSize: "16,384",  type: "BPE",   color: "#a78bfa" },
  { name: "BPE-32K",      vocabSize: "32,768",  type: "BPE",   color: "#34d399" },
  { name: "BPE-64K",      vocabSize: "65,536",  type: "BPE",   color: "#fbbf24" },
  { name: "BPE-128K",     vocabSize: "131,072", type: "BPE",   color: "#f87171" },
  { name: "Byte-BPE",     vocabSize: "8,000",   type: "BBPE",  color: "#60a5fa" },
  { name: "Hybrid Code-Mixed", vocabSize: "Hybrid",  type: "MIXED", color: "#10b981" },
];

const CASE_STUDIES: CaseStudy[] = [
  { 
    label: "Spelling Noise", 
    text: "The model understands context", 
    perturbation: "char-swap", 
    perturbed: "The mdoel undrstands contxt",
    desc: "Simulates human typographical errors. Standard BPE often shatters slightly misspelled words into meaningless individual characters, completely losing the semantic root."
  },
  { 
    label: "OCR Distortion", 
    text: "Tokenization is fundamental", 
    perturbation: "ocr-like", 
    perturbed: "T0ken1zat10n 1s fundament4l",
    desc: "Simulates scanned document artifacts. Inserting digits or symbols inside standard words causes severe syntactic boundary fragmentation."
  },
  { 
    label: "Code-Mixed (Hinglish)", 
    text: "The model performs really well", 
    perturbation: "transliteration", 
    perturbed: "The model bahut acha kaam karta",
    desc: "Tests structural demographic bias. Indian languages written in Latin script lack vocabulary representation, leading to catastrophic Out-Of-Vocabulary (OOV) rates."
  },
  { 
    label: "Boundary Shift", 
    text: "unhappy versus un-happy split", 
    perturbation: "hyphenation", 
    perturbed: "un-happy versus unhappy split",
    desc: "Tests syntactic boundaries. A single punctuation mark like a hyphen can drastically alter the morphological split generated by the BPE algorithm."
  },
];

const TABS = ["Alignment", "Saliency", "Comparison", "Case Studies"] as const;
type Tab = typeof TABS[number];

// ─── Helpers ─────────────────────────────────────────────────────────────────

// Transforms Real API response into our UI structure
function buildGroupsFromApi(tokens: string[], saliencies: number[], text: string): GroupedWord[] {
  const words = text.split(/\s+/).filter(Boolean);
  const groups: GroupedWord[] = [];
  let tIdx = 0;
  let charCursor = 0;

  for (let wi = 0; wi < words.length; wi++) {
    const word = words[wi];
    const startChar = text.indexOf(word, charCursor);
    charCursor = startChar + word.length;

    const wordTokens: SubToken[] = [];
    let salSum = 0;
    let reconstructed = "";
    const targetClean = word.toLowerCase().replace(/[.,!?]/g, "");

    while(tIdx < tokens.length) {
      const rawTok = tokens[tIdx];
      const cleanTok = rawTok.replace("</w>", "").replace("[MIX]_", "");
      const sal = saliencies[tIdx] || 0.1;

      const cs = startChar + reconstructed.length;
      wordTokens.push({ text: rawTok, saliency: sal, idx: tIdx, charStart: cs, charEnd: cs + cleanTok.length });

      reconstructed += cleanTok.toLowerCase();
      salSum += sal;
      tIdx++;

      if (rawTok.includes("</w>")) break;
      // Soft break for BBPE/Router which may not emit </w> tags
      if (reconstructed.length >= targetClean.length && targetClean.length > 0) break;
    }

    groups.push({
      originalWord: word, tokens: wordTokens, totalSaliency: salSum,
      avgSaliency: wordTokens.length ? salSum / wordTokens.length : 0,
      maxAbsSaliency: wordTokens.length ? Math.max(...wordTokens.map(t => Math.abs(t.saliency))) : 0,
      isFragmented: wordTokens.length > 1, wordIdx: wi,
    });
  }
  return groups;
}

function computeMetrics(groups: GroupedWord[], text: string, apiOovRate?: number) {
  if (!groups || groups.length === 0) return { totalTokens: 0, oovRate: 0, fragRate: 0, avgTpW: 0, compressionRatio: 0 };
  
  const allToks = groups.flatMap(g => g.tokens);
  const oovRate = apiOovRate !== undefined ? apiOovRate : (allToks.length ? allToks.filter(t => Math.abs(t.saliency) < 0.05).length / allToks.length : 0);
  const fragRate = groups.length ? groups.filter(g => g.isFragmented).length / groups.length : 0;
  const avgTpW = groups.length ? allToks.length / groups.length : 0;
  const chars = text.replace(/\s/g, "").length;
  const compressionRatio = allToks.length ? chars / allToks.length : 0;
  
  return { totalTokens: allToks.length, oovRate, fragRate, avgTpW, compressionRatio };
}

// ─── UI Helpers ───────────────────────────────────────────────────────────────
const renderTokenText = (text: string, showDot = false) => {
  const isMix = text.includes("[MIX]_");
  const isWordEnd = text.includes("</w>");
  const cleanText = text.replace("[MIX]_", "").replace("</w>", "");

  return (
    <span style={isMix ? { color: "var(--amber)", fontWeight: "bold" } : {}}>
      {cleanText}
      {isMix && <span style={{ fontSize: "8px", verticalAlign: "super", marginLeft: "2px", color: "var(--amber)" }}>[MIX]</span>}
      {showDot && isWordEnd && <span style={{ color: "var(--muted2)", fontSize: "8px", marginLeft: "2px" }}>·</span>}
    </span>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────
export default function TokenizerDashboard() {
  const [inputText, setInputText] = useState("Even the Amazing Spider-Man needs a good tokenizer to navigate the multiverse.");
  const [activeTokenizer, setActiveTokenizer] = useState(6); // Defaults to Smart-Router
  const [activeTab, setActiveTab] = useState<Tab>("Case Studies"); // Start on Case Studies as requested
  const [hoveredWord, setHoveredWord] = useState<number | null>(null);
  const [hoveredToken, setHoveredToken] = useState<number | null>(null);
  
  // Main API State
  const [isLoading, setIsLoading] = useState(false);
  const [realApiData, setRealApiData] = useState<any>(null);

  // Case Study State
  const [caseIdx, setCaseIdx] = useState(0);
  const [isCaseLoading, setIsCaseLoading] = useState(false);
  const [caseResults, setCaseResults] = useState<{ original: any, perturbed: any } | null>(null);

  // Main Fetch from Python Backend
  const handleAnalyze = async (textToAnalyze = inputText) => {
    if (!textToAnalyze.trim()) return;
    setIsLoading(true);
    try {
      const res = await fetch("http://localhost:8000/api/tokenize_all", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: textToAnalyze }),
      });
      const data = await res.json();
      setRealApiData(data);
      setActiveTab("Comparison");
    } catch (error) {
      console.error("Failed to fetch from API", error);
    }
    setIsLoading(false);
  };

  // Dedicated Fetch for Case Studies (Original vs Perturbed)
  const runCaseStudy = async () => {
    setIsCaseLoading(true);
    setCaseResults(null);
    const activeCase = CASE_STUDIES[caseIdx];
    try {
      const [resOrg, resPert] = await Promise.all([
        fetch("http://localhost:8000/api/tokenize_all", {
          method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: activeCase.text }),
        }),
        fetch("http://localhost:8000/api/tokenize_all", {
          method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: activeCase.perturbed }),
        })
      ]);
      const dataOrg = await resOrg.json();
      const dataPert = await resPert.json();
      setCaseResults({ original: dataOrg, perturbed: dataPert });
    } catch (error) {
      console.error("Failed to run case study", error);
    }
    setIsCaseLoading(false);
  };

  const allResults = useMemo(() => {
    if (!realApiData) return TOKENIZERS.map(() => []);
    return TOKENIZERS.map(cfg => {
      const apiMatch = realApiData.find((d: any) => d.name === cfg.name);
      if (apiMatch) return buildGroupsFromApi(apiMatch.tokens, apiMatch.saliency, inputText);
      return [];
    });
  }, [inputText, realApiData]);

  const allMetrics = useMemo(() => {
    return TOKENIZERS.map((cfg, i) => {
      const apiMatch = realApiData?.find((d: any) => d.name === cfg.name);
      return computeMetrics(allResults[i], inputText, apiMatch?.oov_rate);
    });
  }, [allResults, inputText, realApiData]);

  const groups = allResults[activeTokenizer] || [];
  const metrics = allMetrics[activeTokenizer] || { totalTokens: 0, oovRate: 0, fragRate: 0, avgTpW: 0, compressionRatio: 0 };
  const cfg = TOKENIZERS[activeTokenizer];

  const rawTokens = groups.flatMap(g => g.tokens);
  const globalMax = Math.max(...rawTokens.map(t => Math.abs(t.saliency)), 0.001);

  const heatBg = (s: number, alpha = 1) => {
    const a = Math.min(Math.abs(s) / globalMax, 1) * alpha;
    return s > 0 ? `rgba(52,211,153,${a * 0.25})` : s < 0 ? `rgba(248,113,113,${a * 0.22})` : "transparent";
  };
  const heatBorder = (s: number) => {
    const a = Math.min(Math.abs(s) / globalMax, 1);
    return s > 0 ? `rgba(52,211,153,${a * 0.6})` : s < 0 ? `rgba(248,113,113,${a * 0.55})` : "rgba(255,255,255,0.1)";
  };

  const charMap = useMemo(() => {
    if (!realApiData) return [];
    const chars = inputText.split("");
    return chars.map((ch, ci) => {
      const tok = rawTokens.find(t => ci >= t.charStart && ci < t.charEnd);
      return { ch, tok };
    });
  }, [inputText, rawTokens, realApiData]);


  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&family=Bricolage+Grotesque:opsz,wght@12..96,300;12..96,400;12..96,600;12..96,800&display=swap');
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        :root {
          --bg: #0c0c0c; --s1: #131313; --s2: #181818; --s3: #1e1e1e;
          --b0: rgba(255,255,255,0.06); --b1: rgba(255,255,255,0.1); --b2: rgba(255,255,255,0.18);
          --text: #ede8df; --muted: #555; --muted2: #333;
          --mono: 'DM Mono', monospace; --sans: 'Bricolage Grotesque', sans-serif;
          --green: #34d399; --red: #f87171; --amber: #fbbf24; --blue: #60a5fa; --purple: #a78bfa;
        }
        body { background: var(--bg); color: var(--text); font-family: var(--sans); }
        .page { max-width: 1100px; margin: 0 auto; padding: 60px 28px 120px; }

        /* ── topbar ── */
        .topbar { display: flex; align-items: flex-end; justify-content: space-between; border-bottom: 1px solid var(--b0); padding-bottom: 20px; margin-bottom: 36px; gap: 16px; flex-wrap: wrap; }
        .brand { display: flex; flex-direction: column; gap: 3px; }
        .brand-sub { font-family: var(--mono); font-size: 10px; color: var(--muted); letter-spacing: 0.16em; text-transform: uppercase; }
        .brand-name { font-size: 22px; font-weight: 800; letter-spacing: -0.04em; line-height: 1; }
        .brand-course { font-family: var(--mono); font-size: 10px; color: var(--muted); margin-top: 2px; }
        .tok-switcher { display: flex; gap: 6px; flex-wrap: wrap; }
        .tok-btn { font-family: var(--mono); font-size: 11px; padding: 6px 13px; border-radius: 3px; border: 1px solid var(--b0); color: var(--muted); background: transparent; cursor: pointer; transition: all 0.15s; letter-spacing: 0.05em; }
        .tok-btn.active { color: var(--bg); border-color: transparent; font-weight: 500; }

        /* ── input ── */
        .input-row { display: flex; gap: 10px; margin-bottom: 32px; align-items: flex-start; }
        .input-wrap { flex: 1; }
        .field-label { font-family: var(--mono); font-size: 10px; color: var(--muted); letter-spacing: 0.14em; text-transform: uppercase; margin-bottom: 8px; }
        textarea { width: 100%; background: var(--s1); border: 1px solid var(--b0); border-radius: 3px; padding: 14px 16px; font-family: var(--mono); font-size: 13px; font-weight: 300; color: var(--text); resize: none; outline: none; line-height: 1.75; transition: border-color 0.15s; }
        textarea:focus { border-color: var(--b1); }
        .run-btn { font-family: var(--mono); font-size: 11px; font-weight: 500; letter-spacing: 0.1em; padding: 10px 20px; background: var(--text); color: var(--bg); border: none; border-radius: 3px; cursor: pointer; text-transform: uppercase; white-space: nowrap; margin-top: 26px; transition: opacity 0.15s; }
        .run-btn:hover { opacity: 0.85; }
        .run-btn:disabled { opacity: 0.5; cursor: not-allowed; }

        /* ── metrics strip ── */
        .metrics { display: grid; grid-template-columns: repeat(5, 1fr); border: 1px solid var(--b0); border-radius: 3px; overflow: hidden; margin-bottom: 32px; }
        .m-cell { padding: 16px 16px 14px; border-right: 1px solid var(--b0); }
        .m-cell:last-child { border-right: none; }
        .m-label { font-family: var(--mono); font-size: 9px; color: var(--muted); letter-spacing: 0.14em; text-transform: uppercase; margin-bottom: 5px; }
        .m-val { font-size: 28px; font-weight: 800; letter-spacing: -0.04em; line-height: 1; }
        .m-sub { font-family: var(--mono); font-size: 10px; color: var(--muted); margin-top: 3px; }

        /* ── tabs ── */
        .tabs { display: flex; gap: 0; border-bottom: 1px solid var(--b0); margin-bottom: 28px; }
        .tab { font-family: var(--mono); font-size: 11px; padding: 9px 16px; cursor: pointer; color: var(--muted); border-bottom: 2px solid transparent; letter-spacing: 0.06em; transition: all 0.15s; background: transparent; border-top: none; border-left: none; border-right: none; }
        .tab.active { color: var(--text); border-bottom-color: var(--text); }
        .tab:hover:not(.active) { color: #999; }

        /* ── alignment tab ── */
        .char-map { display: flex; flex-wrap: wrap; gap: 2px; margin-bottom: 28px; padding: 18px; background: var(--s1); border: 1px solid var(--b0); border-radius: 3px; }
        .char-cell { display: flex; flex-direction: column; align-items: center; gap: 2px; }
        .char-glyph { font-family: var(--mono); font-size: 14px; color: var(--text); line-height: 1; padding: 2px 3px; border-radius: 2px; border-bottom: 2px solid transparent; transition: all 0.1s; }
        .char-glyph.space { opacity: 0.15; }
        .char-tok-id { font-family: var(--mono); font-size: 7px; color: var(--muted); }

        .word-grid { display: flex; flex-wrap: wrap; gap: 8px; }
        .word-cell { border: 1px solid var(--b0); border-radius: 3px; overflow: hidden; background: var(--s1); transition: border-color 0.15s; min-width: 64px; }
        .word-cell:hover, .word-cell.hl { border-color: var(--b2); }
        .word-head { padding: 7px 10px 5px; border-bottom: 1px solid var(--b0); background: rgba(255,255,255,0.02); }
        .word-raw { font-family: var(--mono); font-size: 11px; font-weight: 500; color: var(--muted); display: block; text-align: center; letter-spacing: 0.03em; }
        .word-badges { display: flex; justify-content: center; gap: 4px; margin-top: 4px; flex-wrap: wrap; }
        .badge { font-family: var(--mono); font-size: 8px; padding: 1px 5px; border-radius: 2px; border: 1px solid; letter-spacing: 0.05em; }
        .b-frag { color: var(--amber); border-color: rgba(251,191,36,0.3); background: rgba(251,191,36,0.07); }
        .b-oov  { color: var(--red);   border-color: rgba(248,113,113,0.3); background: rgba(248,113,113,0.07); }
        .b-clean{ color: var(--green); border-color: rgba(52,211,153,0.3);  background: rgba(52,211,153,0.07);  }
        .tokens-area { display: flex; gap: 4px; padding: 8px 8px 4px; justify-content: center; flex-wrap: wrap; }
        .tok-grp { display: flex; flex-direction: column; align-items: center; gap: 2px; }
        .tok-idx { font-family: var(--mono); font-size: 8px; color: var(--muted2); }
        .tok-chip { font-family: var(--mono); font-size: 12px; padding: 3px 7px; border-radius: 2px; border: 1px solid; color: var(--text); cursor: default; transition: transform 0.1s; white-space: nowrap; }
        .tok-score { font-family: var(--mono); font-size: 9px; }
        .tok-bar { width: 100%; height: 2px; border-radius: 1px; margin-top: 1px; }
        .word-foot { font-family: var(--mono); font-size: 9px; font-weight: 500; text-align: center; padding: 5px 8px 7px; letter-spacing: 0.04em; }
        .pos { color: var(--green); } .neg { color: var(--red); } .neu { color: var(--muted); }

        /* ── saliency tab ── */
        .sal-section { margin-bottom: 32px; }
        .sec-title { font-family: var(--mono); font-size: 10px; color: var(--muted); letter-spacing: 0.14em; text-transform: uppercase; margin-bottom: 14px; padding-bottom: 8px; border-bottom: 1px solid var(--b0); }
        .dist-bars { display: flex; align-items: flex-end; gap: 3px; height: 72px; }
        .d-bar { flex: 1; border-radius: 1px 1px 0 0; min-width: 3px; cursor: pointer; transition: opacity 0.15s; }
        .dist-axis { display: flex; justify-content: space-between; margin-top: 6px; }
        .axis-lbl { font-family: var(--mono); font-size: 9px; color: var(--muted); }
        .heatmap-row { display: flex; gap: 0; flex-wrap: wrap; }
        .heat-cell { width: 28px; height: 28px; display: flex; align-items: center; justify-content: center; font-family: var(--mono); font-size: 9px; border: 1px solid var(--b0); cursor: default; transition: transform 0.1s; position: relative; }
        .heat-cell:hover { transform: scale(1.2); z-index: 10; }
        .rank-row { display: flex; gap: 8px; flex-wrap: wrap; }
        .rank-item { display: flex; align-items: center; gap: 8px; padding: 8px 12px; background: var(--s1); border: 1px solid var(--b0); border-radius: 3px; font-family: var(--mono); font-size: 11px; }
        .rank-n { color: var(--muted); min-width: 16px; }
        .rank-tok { color: var(--text); }
        .rank-bar-bg { width: 80px; height: 4px; background: var(--muted2); border-radius: 2px; overflow: hidden; }
        .rank-bar-fill { height: 100%; border-radius: 2px; }

        /* ── comparison tab ── */
        .cmp-table { width: 100%; border-collapse: collapse; font-family: var(--mono); font-size: 12px; margin-bottom: 28px; }
        .cmp-table th { font-size: 9px; color: var(--muted); letter-spacing: 0.14em; text-transform: uppercase; text-align: left; padding: 8px 12px; border-bottom: 1px solid var(--b0); font-weight: 400; }
        .cmp-table td { padding: 10px 12px; border-bottom: 1px solid var(--b0); color: var(--text); vertical-align: middle; }
        .cmp-table tr:last-child td { border-bottom: none; }
        .cmp-table tr:hover td { background: rgba(255,255,255,0.02); }
        .cmp-dot { width: 8px; height: 8px; border-radius: 2px; display: inline-block; margin-right: 8px; }
        .bar-cell { display: flex; align-items: center; gap: 8px; }
        .bar-bg { height: 6px; background: var(--muted2); border-radius: 3px; overflow: hidden; flex: 1; min-width: 80px; }
        .bar-fg { height: 100%; border-radius: 3px; }

        /* ── case studies ── */
        .case-tabs { display: flex; gap: 6px; margin-bottom: 20px; flex-wrap: wrap; }
        .case-tab { font-family: var(--mono); font-size: 10px; padding: 5px 12px; border-radius: 100px; border: 1px solid var(--b0); color: var(--muted); background: transparent; cursor: pointer; transition: all 0.15s; letter-spacing: 0.04em; }
        .case-tab.active { border-color: var(--amber); color: var(--amber); background: rgba(251,191,36,0.05); }
        
        .cs-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 16px; }
        .cs-panel { background: var(--bg); border: 1px solid var(--b0); border-radius: 4px; padding: 16px; }
        .cs-label { font-family: var(--mono); font-size: 9px; letter-spacing: 0.1em; text-transform: uppercase; margin-bottom: 8px; }
        .cs-text { font-family: var(--mono); font-size: 13px; color: var(--text); margin-bottom: 16px; }
        .cs-tok-row { display: flex; flex-wrap: wrap; gap: 4px; }
        .cs-chip { font-family: var(--mono); font-size: 11px; padding: 3px 6px; border-radius: 2px; border: 1px solid; }

        @keyframes up { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
        .appear { animation: up 0.3s ease both; }

        .empty-state { display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 60px 20px; border: 1px dashed var(--b0); border-radius: 4px; color: var(--muted); font-family: var(--mono); font-size: 12px; text-align: center;}
        
        @media (max-width: 640px) {
          .metrics { grid-template-columns: repeat(3, 1fr); }
          .metrics .m-cell:nth-child(4), .metrics .m-cell:nth-child(5) { border-top: 1px solid var(--b0); }
          .cs-grid { grid-template-columns: 1fr; }
        }
      `}</style>

      <div className="page">
        {/* ── Top bar ── */}
        <div className="topbar">
          <div className="brand">
            <span className="brand-sub">Part 6 · Assignment</span>
            <span className="brand-name">Explainable Tokenizer</span>
            <span className="brand-course">Sub-word Tokenization & Evaluation · rahu230103021@iiitmanipur.ac.in</span>
          </div>
          <div className="tok-switcher">
            {TOKENIZERS.map((t, i) => (
              <button
                key={i}
                className={`tok-btn ${activeTokenizer === i ? "active" : ""}`}
                style={activeTokenizer === i ? { background: t.color } : {}}
                onClick={() => setActiveTokenizer(i)}
              >
                {t.name}
              </button>
            ))}
          </div>
        </div>

        {/* ── Input ── */}
        <div className="input-row">
          <div className="input-wrap">
            <p className="field-label">Input sequence</p>
            <textarea rows={2} value={inputText} onChange={e => setInputText(e.target.value)} />
          </div>
          <button className="run-btn" disabled={isLoading} onClick={() => handleAnalyze(inputText)}>
            {isLoading ? "Fetching API..." : "Analyze →"}
          </button>
        </div>

        {/* ── Tabs & Metrics (Hidden until data is fetched) ── */}
        {!realApiData && activeTab !== "Case Studies" ? (
          <div className="empty-state">
            <p style={{ fontSize: 16, marginBottom: 8, color: "var(--text)" }}>Awaiting Analysis</p>
            <p>Enter text and click "Analyze →" to fetch live BPE metrics from the Python backend.</p>
          </div>
        ) : (
          <>
            {(activeTab === "Alignment" || activeTab === "Saliency" || activeTab === "Comparison") && realApiData && (
              <div className="metrics appear">
                {[
                  { label: "Tokens",       val: metrics.totalTokens,                         color: cfg.color,      sub: cfg.name },
                  { label: "Avg tok/word", val: metrics.avgTpW.toFixed(2),                   color: "var(--text)",  sub: "fragmentation index" },
                  { label: "OOV rate",     val: (metrics.oovRate * 100).toFixed(1) + "%",    color: "var(--red)",   sub: "out-of-vocab" },
                  { label: "Frag rate",    val: (metrics.fragRate * 100).toFixed(1) + "%",   color: "var(--amber)", sub: "split words" },
                  { label: "Compression",  val: metrics.compressionRatio.toFixed(2) + "×",   color: "var(--green)", sub: "chars / token" },
                ].map((m, i) => (
                  <div className="m-cell" key={i}>
                    <p className="m-label">{m.label}</p>
                    <p className="m-val" style={{ color: m.color }}>{m.val}</p>
                    <p className="m-sub">{m.sub}</p>
                  </div>
                ))}
              </div>
            )}

            <div className="tabs">
              {TABS.map(t => (
                <button key={t} className={`tab ${activeTab === t ? "active" : ""}`} onClick={() => setActiveTab(t)}>{t}</button>
              ))}
            </div>

            {/* ══════════════ TAB: Alignment ══════════════ */}
            {activeTab === "Alignment" && realApiData && (
              <div className="appear">
                <p className="sec-title" style={{ marginBottom: 12 }}>Character → Token alignment map</p>
                <div className="char-map">
                  {charMap.map((c, i) =>
                    c.ch === " " ? (
                      <div key={i} style={{ width: 10 }} />
                    ) : (
                      <div className="char-cell" key={i}>
                        <span
                          className={`char-glyph`}
                          style={{
                            borderBottomColor: c.tok ? heatBorder(c.tok.saliency) : "transparent",
                            background: c.tok ? heatBg(c.tok.saliency, 0.8) : "transparent",
                          }}
                          title={c.tok ? `Token #${c.tok.idx}: "${c.tok.text.replace("</w>","").replace("[MIX]_","")}" · sal: ${c.tok.saliency.toFixed(4)}` : undefined}
                        >
                          {c.ch}
                        </span>
                        <span className="char-tok-id">{c.tok ? c.tok.idx : ""}</span>
                      </div>
                    )
                  )}
                </div>

                <p className="sec-title" style={{ marginBottom: 14 }}>Word-level grouping · hover to cross-highlight</p>
                <div className="word-grid">
                  {groups.map((w, wi) => (
                    <div
                      className={`word-cell ${hoveredWord === wi ? "hl" : ""}`}
                      key={wi}
                      onMouseEnter={() => setHoveredWord(wi)}
                      onMouseLeave={() => setHoveredWord(null)}
                    >
                      <div className="word-head">
                        <span className="word-raw">{w.originalWord}</span>
                        <div className="word-badges">
                          {w.isFragmented && <span className="badge b-frag">{w.tokens.length}× split</span>}
                          {!w.isFragmented && <span className="badge b-clean">intact</span>}
                        </div>
                      </div>
                      <div className="tokens-area">
                        {w.tokens.map((t, ti) => (
                          <div className="tok-grp" key={ti}
                            onMouseEnter={() => setHoveredToken(t.idx)}
                            onMouseLeave={() => setHoveredToken(null)}
                          >
                            <span className="tok-idx">#{t.idx}</span>
                            <span
                              className="tok-chip"
                              style={{ background: heatBg(t.saliency), borderColor: heatBorder(t.saliency) }}
                              title={`Token #${t.idx} · saliency: ${t.saliency.toFixed(6)}\nChar span: [${t.charStart}–${t.charEnd}]`}
                            >
                              {renderTokenText(t.text)}
                            </span>
                            <span className={`tok-score ${t.saliency > 0.05 ? "pos" : t.saliency < -0.05 ? "neg" : "neu"}`}>
                              {t.saliency > 0 ? "+" : ""}{t.saliency.toFixed(2)}
                            </span>
                            <div className="tok-bar" style={{
                              background: t.saliency > 0 ? "var(--green)" : t.saliency < 0 ? "var(--red)" : "var(--muted2)",
                              width: `${(Math.abs(t.saliency) / globalMax) * 100}%`,
                              minWidth: 2,
                            }} />
                          </div>
                        ))}
                      </div>
                      <div className={`word-foot ${w.totalSaliency > 0.05 ? "pos" : w.totalSaliency < -0.05 ? "neg" : "neu"}`}>
                        Σ {w.totalSaliency > 0 ? "+" : ""}{w.totalSaliency.toFixed(3)} · avg {w.avgSaliency.toFixed(2)} · max {w.maxAbsSaliency.toFixed(2)}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* ══════════════ TAB: Saliency ══════════════ */}
            {activeTab === "Saliency" && realApiData && (
              <div className="appear">
                <div className="sal-section">
                  <p className="sec-title">Token saliency distribution · all {rawTokens.length} tokens</p>
                  <div className="dist-bars">
                    {rawTokens.map((t, i) => {
                      const h = Math.max((Math.abs(t.saliency) / globalMax) * 72, 4);
                      const inHovered = hoveredWord !== null && groups[hoveredWord]?.tokens.some(tok => tok.idx === i);
                      return (
                        <div key={i} className="d-bar"
                          style={{
                            height: h, background: t.saliency > 0 ? "var(--green)" : "var(--red)",
                            opacity: hoveredWord !== null ? (inHovered ? 1 : 0.1) : 0.65,
                          }}
                          onMouseEnter={() => { const wIdx = groups.findIndex(g => g.tokens.some(tok => tok.idx === i)); setHoveredWord(wIdx); }}
                          onMouseLeave={() => setHoveredWord(null)}
                          title={`#${i} "${t.text.replace("</w>","").replace("[MIX]_","")}" · ${t.saliency.toFixed(4)}`}
                        />
                      );
                    })}
                  </div>
                  <div className="dist-axis">
                    <span className="axis-lbl">token 0</span>
                    <span className="axis-lbl">← hover bar to highlight word →</span>
                    <span className="axis-lbl">token {rawTokens.length - 1}</span>
                  </div>
                </div>

                <div className="sal-section">
                  <p className="sec-title">2-D saliency heatmap · token index × magnitude</p>
                  <div className="heatmap-row">
                    {rawTokens.map((t, i) => (
                      <div key={i} className="heat-cell"
                        style={{ background: heatBg(t.saliency, 1.5), borderColor: heatBorder(t.saliency) }}
                        title={`#${i} "${t.text.replace("</w>","").replace("[MIX]_","")}" · ${t.saliency.toFixed(4)}`}
                      >
                        <span style={{ fontSize: 8, color: t.saliency > 0 ? "var(--green)" : t.saliency < 0 ? "var(--red)" : "var(--muted)", fontFamily: "var(--mono)" }}>
                          {t.saliency.toFixed(1)}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="sal-section">
                  <p className="sec-title">Top 10 tokens by absolute saliency</p>
                  <div className="rank-row">
                    {[...rawTokens].sort((a, b) => Math.abs(b.saliency) - Math.abs(a.saliency)).slice(0, 10).map((t, i) => (
                      <div className="rank-item" key={i}>
                        <span className="rank-n">{i + 1}</span>
                        <span className="rank-tok" style={{ borderBottom: `2px solid ${t.saliency > 0 ? "var(--green)" : "var(--red)"}` }}>
                          {renderTokenText(t.text)}
                        </span>
                        <div className="rank-bar-bg">
                          <div className="rank-bar-fill" style={{
                            width: `${(Math.abs(t.saliency) / globalMax) * 100}%`,
                            background: t.saliency > 0 ? "var(--green)" : "var(--red)",
                          }} />
                        </div>
                        <span style={{ fontFamily: "var(--mono)", fontSize: 10, color: t.saliency > 0 ? "var(--green)" : "var(--red)" }}>
                          {t.saliency > 0 ? "+" : ""}{t.saliency.toFixed(3)}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* ══════════════ TAB: Comparison ══════════════ */}
            {activeTab === "Comparison" && realApiData && (
              <div className="appear">
                <p className="sec-title" style={{ marginBottom: 16 }}>Cross-tokenizer metrics for same input</p>
                <table className="cmp-table">
                  <thead>
                    <tr>
                      <th>Tokenizer</th><th>Vocab</th><th>Type</th><th>Tokens</th>
                      <th>Avg tok/word</th><th>OOV rate</th><th>Frag rate</th>
                      <th>Latency (ms)</th><th>Throughput (t/s)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {TOKENIZERS.map((t, i) => {
                      const m = allMetrics[i];
                      const apiMatch = realApiData?.find((d: any) => d.name === t.name);
                      const latency = apiMatch?.latency_ms || 0;
                      const throughput = latency > 0 ? Math.round((m.totalTokens / latency) * 1000) : 0;
                      
                      return (
                        <tr key={i}>
                          <td>
                            <span className="cmp-dot" style={{ background: t.color }} />
                            <strong>{t.name}</strong>
                          </td>
                          <td style={{ fontFamily: "var(--mono)", color: "var(--muted)", fontSize: 11 }}>{t.vocabSize}</td>
                          <td style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--muted)" }}>{t.type}</td>
                          <td style={{ fontFamily: "var(--mono)" }}>{m.totalTokens}</td>
                          <td>
                            <div className="bar-cell">
                              <span style={{ fontFamily: "var(--mono)", fontSize: 12, minWidth: 32 }}>{m.avgTpW.toFixed(2)}</span>
                              <div className="bar-bg"><div className="bar-fg" style={{ width: `${Math.min(m.avgTpW / 4 * 100, 100)}%`, background: t.color }} /></div>
                            </div>
                          </td>
                          <td style={{ fontFamily: "var(--mono)", color: "var(--red)" }}>{(m.oovRate * 100).toFixed(1)}%</td>
                          <td style={{ fontFamily: "var(--mono)", color: "var(--amber)" }}>{(m.fragRate * 100).toFixed(1)}%</td>
                          <td style={{ fontFamily: "var(--mono)", color: latency > 2 ? "var(--amber)" : "var(--green)" }}>{latency.toFixed(2)}</td>
                          <td style={{ fontFamily: "var(--mono)", color: "var(--blue)" }}>{throughput.toLocaleString()}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>

                <p className="sec-title" style={{ marginBottom: 14 }}>Segmentation side-by-side for: "{inputText.split(" ").slice(0, 5).join(" ")}…"</p>
                <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                  {TOKENIZERS.map((t, i) => (
                    <div key={i} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", background: "var(--s1)", border: "1px solid var(--b0)", borderRadius: 3 }}>
                      <span style={{ fontFamily: "var(--mono)", fontSize: 10, color: t.color, minWidth: 72, letterSpacing: "0.05em" }}>{t.name}</span>
                      <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                        {(allResults[i] || []).flatMap(w => w.tokens).slice(0, 14).map((tok, j) => (
                          <span key={j} style={{ fontFamily: "var(--mono)", fontSize: 11, padding: "2px 6px", borderRadius: 2, border: `1px solid ${tok.text.includes("</w>") ? "rgba(255,255,255,0.12)" : "rgba(255,255,255,0.05)"}`, color: tok.text.includes("</w>") ? "var(--text)" : "var(--muted)", background: tok.text.includes("</w>") ? "rgba(255,255,255,0.03)" : "transparent" }}>
                            {renderTokenText(tok.text, true)}
                          </span>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* ══════════════ TAB: Case Studies (Self-Contained) ══════════════ */}
            {activeTab === "Case Studies" && (
              <div className="appear">
                <p className="sec-title" style={{ marginBottom: 16 }}>Live Edge Case Analysis</p>
                
                <div className="case-tabs">
                  {CASE_STUDIES.map((c, i) => (
                    <button key={i} className={`case-tab ${caseIdx === i ? "active" : ""}`} onClick={() => { setCaseIdx(i); setCaseResults(null); }}>
                      {c.label}
                    </button>
                  ))}
                </div>

                <div style={{ background: "var(--s1)", border: "1px solid var(--b0)", borderRadius: 4, padding: "24px" }}>
                  <div style={{ marginBottom: 20 }}>
                    <h3 style={{ fontSize: 16, color: "var(--text)", marginBottom: 8 }}>{CASE_STUDIES[caseIdx].label} — <span style={{color:"var(--amber)", fontSize: 12, fontFamily: "var(--mono)", border: "1px solid var(--amber)", padding: "2px 6px", borderRadius: 3}}>{CASE_STUDIES[caseIdx].perturbation}</span></h3>
                    <p style={{ fontSize: 13, color: "#999", lineHeight: 1.5 }}>{CASE_STUDIES[caseIdx].desc}</p>
                  </div>

                  <div className="cs-grid">
                    <div className="cs-panel">
                      <p className="cs-label" style={{ color: "var(--green)" }}>Original</p>
                      <p className="cs-text">{CASE_STUDIES[caseIdx].text}</p>
                      {caseResults && (
                        <div className="cs-tok-row">
                          {buildGroupsFromApi(caseResults.original.find((d:any) => d.name === cfg.name)?.tokens || [], [], CASE_STUDIES[caseIdx].text)
                            .flatMap(g => g.tokens).map((t, i) => (
                            <span key={i} className="cs-chip" style={{ borderColor: "rgba(52,211,153,0.3)", background: "rgba(52,211,153,0.05)", color: "var(--text)" }}>
                              {renderTokenText(t.text)}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                    
                    <div className="cs-panel" style={{ borderColor: "rgba(251,191,36,0.3)" }}>
                      <p className="cs-label" style={{ color: "var(--amber)" }}>Perturbed</p>
                      <p className="cs-text">{CASE_STUDIES[caseIdx].perturbed}</p>
                      {caseResults && (
                        <div className="cs-tok-row">
                          {buildGroupsFromApi(caseResults.perturbed.find((d:any) => d.name === cfg.name)?.tokens || [], [], CASE_STUDIES[caseIdx].perturbed)
                            .flatMap(g => g.tokens).map((t, i) => (
                            <span key={i} className="cs-chip" style={{ borderColor: "rgba(251,191,36,0.5)", background: "rgba(251,191,36,0.1)", color: "var(--text)" }}>
                              {renderTokenText(t.text)}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 24, paddingTop: 20, borderTop: "1px solid var(--b0)" }}>
                    <p style={{ fontSize: 11, fontFamily: "var(--mono)", color: "var(--muted)" }}>
                      Currently evaluating using: <strong style={{color: cfg.color}}>{cfg.name}</strong>
                    </p>
                    <button 
                      onClick={runCaseStudy} 
                      disabled={isCaseLoading}
                      style={{ padding: "10px 20px", background: "var(--text)", color: "var(--bg)", border: "none", borderRadius: 3, cursor: isCaseLoading ? "not-allowed" : "pointer", fontFamily: "var(--mono)", fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.1em" }}
                    >
                      {isCaseLoading ? "Analyzing Edge Case..." : "Run Live Comparison →"}
                    </button>
                  </div>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </>
  );
}  